# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e60d4ecb4ab9ea934ebb99544bc2c80ec5c44194884895459263b22815c7c2ec5efbe616969deeb26a802696d45be6fa91e877c66514b4d06d49e0ee2420046

test:
  secret_key_base: 621cb9d8df29c99c27624a5a99a5b3e4806da9b80d39da5ddf74c25e66313bb883b5c0e5e098b802e92305bf2f404f3356c843331e277238c80c14c4f57a26d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
